title: Chess Image Generation
description: "Synthetic-to-real image translation for chessboard images"
url: "https://bhk-imagen.github.io"
baseurl: "/BHK-ImaGen" 

remote_theme: jekyll/minima

author:
  name: Yoav Baider Klein, Maor Haak, Guy Kouchly
  email: yoavbaider@gmail.com, Maorhaak2@gmail.com, guykuh@gmail.com

social:
  github: Yoav-Baider-Klein, Maorhaak2, Guy Kouchly

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:

  skin: classic


