title: Chess Image Generation
description: "Synthetic-to-real image translation for chessboard images"
url: "https://github.com/BHK-ImaGen" 
baseurl: ""                        

theme: minima

author:
  name: Yoav Baider Klein, Maor Haak, Guy Kouchly
  email: yoavbaider@gmail.com, Maorhaak2@gmail.com, guykuh@gmail.com

social:
  github: Yoav-Baider-Klein, Maorhaak2, Guy Kouchly

markdown: kramdown

plugins:
  - jekyll-feed 

minima:

  skin: classic
